/*
Project: SQL Sales & HR Analytics
Dataset: AdventureWorks2019
Tool: Azure Data Studio

Author: Nguyen Thi Phuong Trang

This script answers key business questions related to:
- Sales performance
- Customer contribution
- Revenue trends
- HR workforce distribution
*/

-- =========================================================
-- CASE STUDY 1: SALES PERFORMANCE ANALYSIS
-- =========================================================

-- 1. Revenue by Territory (Year 2013)
-- Objective:
-- Calculate total revenue generated by each sales territory
-- to evaluate regional performance and identify key markets.

USE AdventureWorks2019;
GO

SELECT ST.TerritoryID, ST.Name TerritoryName, SUM(SOH.TotalDue) TotalRevenue
FROM Sales.SalesOrderHeader SOH
LEFT JOIN Sales.SalesTerritory ST
    ON ST.TerritoryID = SOH.TerritoryID
WHERE SOH.OrderDate >= '2013-01-01'
    AND SOH.OrderDate < '2014-01-01'
GROUP BY ST.TerritoryID, ST.Name
;
-- 2. Top 5 Best-Selling Products (Year 2013)
-- Objective:
-- Identify the five products generating the highest revenue
-- to determine product performance and revenue concentration.

SELECT TOP 5 SOD.ProductID, SUM(SOD.LineTotal) SalesAmount
FROM Sales.SalesOrderDetail SOD
LEFT JOIN Sales.SalesOrderHeader SOH
    ON SOD.SalesOrderID = SOH.SalesOrderID
WHERE SOH.OrderDate >= '2013-01-01'
    AND SOH.OrderDate < '2014-01-01'
GROUP BY SOD.ProductID
ORDER BY SUM(SOD.LineTotal) DESC
;
-- 3. Highest Spending Customer per Month (Year 2013)
-- Objective:
-- Determine the customer with the highest total spending
-- in each month to identify high-value contributors.

WITH Ranking_Rev AS
(
    SELECT  CustomerID, MONTH(OrderDate) MonthOrder, YEAR(OrderDate) YearOrder, SUM(TotalDue) Total_Due,
            ROW_NUMBER() OVER(PARTITION BY YEAR(OrderDate), MONTH(OrderDate) ORDER BY SUM(TotalDue) DESC) Ranking
    FROM Sales.SalesOrderHeader SOH
    WHERE SOH.OrderDate >= '2013-01-01'
        AND SOH.OrderDate < '2014-01-01'
    GROUP BY CustomerID, MONTH(OrderDate), YEAR(OrderDate)
)
SELECT MonthOrder, YearOrder, CustomerID, Total_Due
FROM Ranking_Rev
WHERE Ranking = 1
;
-- 4. Monthly Revenue Trend (Year 2013)
-- Objective:
-- Identify the months with the highest and lowest revenue
-- to evaluate seasonality and revenue fluctuation patterns.

WITH RevenueByMonth AS
(
    SELECT
        MONTH(OrderDate) MonthOrder,
        YEAR(OrderDate) YearOrder,
        SUM(TotalDue) SalesAmount,
        ROW_NUMBER() OVER(PARTITION BY YEAR(OrderDate) ORDER BY SUM(TotalDue) DESC) Max_Revenue,
        ROW_NUMBER() OVER(PARTITION BY YEAR(OrderDate) ORDER BY SUM(TotalDue) ASC) Min_Revenue
    FROM Sales.SalesOrderHeader
    WHERE OrderDate >= '2013-01-01'
        AND OrderDate < '2014-01-01'
    GROUP BY MONTH(OrderDate), YEAR(OrderDate)
)

SELECT YearOrder, MonthOrder, SalesAmount, 'Highest' Revenue_Group
FROM RevenueByMonth
WHERE Max_Revenue = 1
UNION ALL
SELECT YearOrder, MonthOrder, SalesAmount, 'Lowest' Revenue_Group
FROM RevenueByMonth
WHERE Min_Revenue = 1
;
-- 5. Salesperson Contribution & Ranking (Year 2013)
-- Objective:
-- Calculate each salesperson’s revenue contribution ratio
-- and rank them based on total revenue performance.

SELECT
    SalesPersonID,
    SUM(TotalDue) SalesAmount,
    SUM(SUM(TotalDue)) OVER() Revenue_2013,
    CAST(SUM(TotalDue) AS DECIMAL(18,2)) / SUM(SUM(TotalDue)) OVER() Ratio,
    RANK() OVER(ORDER BY SUM(TotalDue) DESC) Ranking
FROM Sales.SalesOrderHeader
WHERE OrderDate >= '2013-01-01'
  AND OrderDate < '2014-01-01'
  AND SalesPersonID IS NOT NULL
GROUP BY SalesPersonID
;
-- =========================================================
-- CASE STUDY 2: HUMAN RESOURCES ANALYTICS
-- =========================================================
-- 1. Headcount Distribution by Department
-- Objective:
-- Analyze the number of active employees in each department
-- to understand workforce allocation and department size.

SELECT EDH.DepartmentID, D.Name, COUNT(EDH.BusinessEntityID) Number_Of_Employees
FROM HumanResources.EmployeeDepartmentHistory EDH
LEFT JOIN HumanResources.Department D
    ON D.DepartmentID = EDH.DepartmentID
WHERE EndDate IS NULL
GROUP BY EDH.DepartmentID, D.Name
ORDER BY COUNT(EDH.BusinessEntityID) DESC

;
-- 2. Department with the Lowest Headcount
-- Objective:
-- Identify departments with the smallest workforce
-- to support organizational review and planning decisions.

WITH Employees_Department AS
(
    SELECT 
        DepartmentID,
        COUNT(BusinessEntityID) Number_Of_Employees,
        RANK() OVER(ORDER BY COUNT(BusinessEntityID) ASC) Ranking
    FROM HumanResources.EmployeeDepartmentHistory
    WHERE EndDate IS NULL
    GROUP BY DepartmentID
)
SELECT DepartmentID, Number_Of_Employees
FROM Employees_Department
WHERE Ranking = 1
;
-- 3. Top 5 Longest-Tenured Employees (as of 2015)
-- Objective:
-- Calculate employee tenure and identify individuals
-- with the longest service duration within the company.

SELECT TOP 5
    CONCAT_WS(' ',P.FirstName,P.MiddleName,P.LastName) FullName,
    E.JobTitle,
    D.Name Department_Name,
    DATEDIFF(YEAR, E.HireDate, '2015-12-31') YearsOfService
FROM HumanResources.EmployeeDepartmentHistory EDH
LEFT JOIN Person.Person P
    ON P.BusinessEntityID = EDH.BusinessEntityID
LEFT JOIN HumanResources.Employee E
    ON E.BusinessEntityID = EDH.BusinessEntityID
LEFT JOIN HumanResources.Department D
    ON D.DepartmentID = EDH.DepartmentID
WHERE EndDate IS NULL
ORDER BY YearsOfService DESC

-- 4. User-Defined Function: fn_EmployeeWorkAge
-- Objective:
-- Create a scalar function to compute employee tenure
-- based on HireDate up to December 31, 2015.

CREATE FUNCTION dbo.fn_EmployeeWorkAge (
    @BusinessEntityID INT
)
RETURNS INT
AS
BEGIN
    DECLARE @YearsOfService INT;

    SELECT @YearsOfService = DATEDIFF(YEAR, E.HireDate, '2015-12-31')
    FROM HumanResources.Employee E
    WHERE E.BusinessEntityID = @BusinessEntityID;

    RETURN @YearsOfService;

END;

SELECT dbo.fn_EmployeeWorkAge(224) Years_Of_Service
;
-- 5. Job Title Distribution
-- Objective:
-- Analyze job title distribution to identify roles
-- with the highest and lowest number of employees.

WITH Job_Count AS
(
    SELECT
        JobTitle,
        COUNT(E.BusinessEntityID) Employee_Count,
        RANK() OVER(ORDER BY COUNT(E.BusinessEntityID) DESC) Most_Ranking,
        RANK() OVER(ORDER BY COUNT(E.BusinessEntityID) ASC) Lowest_Ranking
    FROM HumanResources.Employee E
    LEFT JOIN HumanResources.EmployeeDepartmentHistory EDH
        ON E.BusinessEntityID = EDH.BusinessEntityID
    WHERE EDH.EndDate IS NULL
    GROUP BY JobTitle
)

SELECT JobTitle, Employee_Count, 'Highest Headcount' as Phan_loai
FROM Job_Count
WHERE Most_Ranking = 1
UNION ALL
SELECT JobTitle, Employee_Count, 'Lowest Headcount' as Phan_loai
FROM Job_Count
WHERE Lowest_Ranking = 1
